# Generated by Django 4.0.3 on 2022-09-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
